#!/bin/bash

red="\e[1;31m"
green="\e[1;32m"
yellow="\e[1;33m"
blue="\e[1;34m"
reset="\e[0m"

function print_success (){
    printf "${green}$1${reset}"
}

function print_warning (){
    printf "${yellow}$1${reset}"
}

function print_info (){
    printf "${blue}$1${reset}"
}

function print_error (){
    printf "${red}$1${reset}"
}

