version: '3'

services:
  nodejs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.df
    image: hb/nodejs
    container_name: nodejs
    hostname: nodejs.hopebaytech.com
    volumes:
      - ./data/shared:/data/shared:rw
      - ./data/nodejs:/data/nodejs:rw
    #environment:
    #  SERVICE_DISCOVERY: env
    #ports:
    #  - 172.16.0.100:4568:4568
    #network_mode: host
    #extra_hosts:
    #  - google:8.8.8.8

networks:
  default:
    external:
      name: it_service
