version: '3'

services:
  nodejs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.df
    image: environment/nodejs
    container_name: nodejs
    hostname: nodejs.tp.office.openfind.com
    volumes:
      - ./data/shared:/data/shared:rw
      - ./data/nodejs:/data/nodejs:rw
    #environment:
    #  SERVICE_DISCOVERY: env
    ports:
      - 4200:4200
    #network_mode: host
    #extra_hosts:
    #  - google:8.8.8.8

networks:
  default:
    external:
      name: it_service
